### ISSUE TITLE
Add vgmplay to the web interface

### ISSUE THREAD

**Issue by GeoNeilUK** [sam-ludlow/mame-ao#10]
I just discovered that MAME has a VGM player, but doesn't seem to appear anywhere in the web interface.  

I'll be honest, I do get better perfromance adding components to foobar2000 or using ZXTune, but it is there and at the moment, I have to type vgmplay in the MAME shell.  

I'm not sure if this would fit with the purpose of MAME-AO as the VGM player is internal to MAME rather than a ROM you'd download from archive.org, but having a link from within the web interface tp the player would be nice!

**Comment by sam-ludlow** [comment]
Closing

Not sure if the UI is clear enough for users to notice the sections?

May add feature in future, maybe a help pop-up for first use?
