### ISSUE TITLE
SQlite lock, first run issues.

### ISSUE THREAD

**Issue by cewatkins** [sam-ludlow/mame-ao#12]
So, got this thing yesterday, I've put it ona view machines, some *nix, other is winblows. Winblows works as expected, and I could use and pass the dircopy to *nix, (Because it would do this on instaLL.)

 wineserver: file_set_error() can't map error: Function not implemented

!!! FATAL ERROR: database is locked
database is locked

code = Busy (5), message = System.Data.SQLite.SQLiteException (0x87AF00AA): dat
abase is locked
database is locked
  at System.Data.SQLite.SQLite3.Prepare (

#### Also, it ends up being 0 bytes for the file, I assume that the rebuild after data change cause it to re-sync lie you state. Uh, also, I'm using bottles and other whiney  attempts..  
But I found the product cause I would use btfs similarly, but yeah, the size and availability on the scene, reminds me when it was 300 baud.. So this works pretty slick. the sym link and/or/a delta addition would be intersting.. Oh, yeah, proper game pick for the readme pic..

**Comment by sam-ludlow** [comment]
Hello @cewatkins thanks for the feedback.

I've not attempted to run on anything other than Windows but it sounds interesting and would to get it working.

Looks like some sort of SQLite problem, mame-ao writes out a zero byte file to create a new empty database, before calling any SQLite functions, maybe this is a problem?

So you are running Wine? Do the Windows MAME binaries run OK on Wine?

Cheers
Sam

**Comment by sam-ludlow** [comment]
You could copy the SQLite DBs from a windows installation (with same versions) to see if that is the problem.

**Comment by sam-ludlow** [comment]
Hello re. symbolic links.

mame-ao just attempts to create a symbolic link to test if enabled.
https://github.com/sam-ludlow/mame-ao/blob/main/source/MameAO.cs#L170

Linking is done by spawning a cmd.exe then using the "mklink" command.
https://github.com/sam-ludlow/mame-ao/blob/main/source/Tools.cs#L286

This was the only way I could get satisfactory results when it came to UTF8 encoding of filenames.

So probably not very portable to *nix.

I will load a Linux box at some point and have a play.
