### ISSUE TITLE
Program crashes on startup

### ISSUE THREAD

**Issue by clydemystik325** [sam-ludlow/mame-ao#13]
When I try to open mame-ao, it will show this message:

!!! FATAL ERROR: Response status code does not indicate success: 403 (rate limit exceeded).

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Spludlow.MameAO.Tools.Query(HttpClient client, String url)
   at Spludlow.MameAO.MameAOProcessor.Initialize()
   at Spludlow.MameAO.MameAOProcessor.Run()

What do I do to fix this?

**Comment by sam-ludlow** [comment]
Hello @clydemystik325 sorry to hear that.

Can you provide a bit more of the output please? I'm not sure at what stage this is failing?

It a problem with the remote server (github.com, archive.org, whatever) "rate limit exceeded" not seen that one myself.

You can probably just try again later. Rate limits are normally tied to an IP address and they expire after a while.

Cheers
Sam

**Comment by sam-ludlow** [comment]
Hello mamo-ao does not handle network issues very well, if something is not reachable on start-up the program will not start. No retrying and nothing get queued.

I may improve handling for network problems in the future, but at the end of the day if the network is broken it can't download assets anyway.

So to sum up if your network is flaky you will have problems.

Cheers
Sam

**Comment by sam-ludlow** [comment]
Closing ticket.

I have slightly improved handling of duff archive.org items.
