### ISSUE TITLE
Add saturn, psx, and dc roms

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [sam-ludlow/mame-ao#14]
more consoles do have chd roms, and i would like to test out saturn, psx, and dreamcast, I found one game at full 100 speed for dreamcast, namco museum.
https://archive.org/download/mame-sl-chd-psx
https://archive.org/download/mame-sl-chd-saturn
https://archive.org/download/mame-sl-chd-dc

**Comment by sam-ludlow** [comment]
Hello noted I was thinking about adding more SL CHDs.

Want to change it a bit so the archive.org items are only queried when used, rather than loading the lot at start-up.

**Comment by sam-ludlow** [comment]
Hello @Iamthebestintheworld222 

I have implemented this in 1.80.

Could you provide a list of a few games from each of the new CHD SL please?

I'd like to test a few myself, shooters if possible?

Cheers
Sam

**Comment by Iamthebestintheworld222** [comment]
psu ffant7 final fantasy 7
psu tf5 thunder force 5
saturnjp jungrhyt Jung rhythm
dc namcoms namco museum
Also try
segacd keio keio flying squadron

**Comment by Iamthebestintheworld222** [comment]
https://archive.org/details/mame-sl-chd-segacd

**Comment by sam-ludlow** [comment]
Hello @Iamthebestintheworld222 

I have included all the CHD SLs from here https://archive.org/details/@tuffytdog

Closing ticket.

Cheers
Sam
