### ISSUE TITLE
Add samples and artwork download

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [sam-ludlow/mame-ao#15]
Some games do require artwork to look better like space invaders, and games use samples like gaplus and rally-x for the explosion sound or zaxxon and carnival for sound effects in general. Could you add support for them
https://archive.org/download/mame-support/Support/Samples/
https://archive.org/download/mame-support/Support/Artworks/
https://archive.org/download/mame-support/Support/ArtworksAll/
https://archive.org/download/mame-support/Support/ArtworksAlt/
https://archive.org/download/mame-support/Support/ArtworksWideScreen/

**Comment by sam-ludlow** [comment]
Hello, yes I will be looking into this for sure.

Just for the rally-x explosion if nothing else.

**Comment by paulmortlock** [comment]
I get this when I run it any suggestions?

Creating machine performance caches......done
Extracting MAME software XML C:\Mame-ao\0264\_software.xml ...drc_cache: Error allocating virtual memory

!!! FATAL ERROR: ExtractXML Bad exit code

**Comment by paulmortlock** [comment]
Loading XML C:\Mame-ao\0264\_software.xml ...
!!! FATAL ERROR: Unexpected end of file has occurred. The following elements are not closed: softwarelists. Line 1251074, position 1.

**Comment by sam-ludlow** [comment]
Hello @paulmortlock 

Sounds like you ran out of memory when extracting the software XML so the file was there but was incomplete the next time you ran it failed loading the XML.

Ensure you have enough RAM available.

To fix your mame-ao delete these 4 files and run again.

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/0323ed6b-48a2-4510-8a8e-8124e0e7a205)

Cheers
Sam

**Comment by sam-ludlow** [comment]
Samples is implemented in 1.83.

I will be doing artwork next.

Cheers

**Comment by sam-ludlow** [comment]
Been implementing artwork and to be honest I'm not that impressed.

Yes "invaders" looks pretty cool but I'd rather just play full screen.

I think I'll make artwork optional somehow?

**Comment by sam-ludlow** [comment]
Well I've never used them before up until now.

Still to find out what exactly is available. I'm guessing some stuff really needs it like LCD games, like Game and watch?

Next release will have it in. If you pull the latest code and build mame-ao yourself you can have a sneak peek.

https://github.com/sam-ludlow/mame-ao/commit/8c060f9d5597864c8ad6bc00485f1355c456a475

Example "invaders"

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/721e3857-1403-497e-946f-4340119204d8)

**Comment by sam-ludlow** [comment]
Defiantly shouldn't be switched on by default.

The first one I tried was "005" and I wasn't very impressed.

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/d486f42b-0f90-4132-85bf-58e93e041cde)

**Comment by paulmortlock** [comment]
Oh dear indeed.

**Comment by sam-ludlow** [comment]
Artwork is implemented in 1.86 you have to switch it on.

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/238597ef-b7cc-4bf0-bb8c-08341e9199d3)

Its just using the offical artwork at the moments I will add options for other artwork types later.

**Comment by paulmortlock** [comment]
Good 👍

**Comment by sam-ludlow** [comment]
Other artwork type implemented in 1.87.

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/371f2cc6-bc0a-4617-aec0-f987fa05f583)

**Comment by paulmortlock** [comment]
Excellent which ones have artwork an example to try 😀

**Comment by sam-ludlow** [comment]
I'll add some sort of artwork report at some point but for now if you look at the raw data you can spot them.

See the 3 links here https://github.com/sam-ludlow/mame-ao?tab=readme-ov-file#artwork-xml

Seems like the "Alt" set has some pretty cool stuff in.

for example "batsugun" the joysticks even move.

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/a389c089-cd8a-4916-9adc-8b02a00201e3)

Again all very good and well, but in my opinion nothing more that a novelty, I can't see myself ever playing anything with it enabled.

**Comment by paulmortlock** [comment]
Very cool Sam

![image](https://github.com/sam-ludlow/mame-ao/assets/7123294/06ba473a-7749-410b-9156-4a251dd905f2)

**Comment by sam-ludlow** [comment]
Sweet I'm closing ticket looks like it works.
