### ISSUE TITLE
Mis-spelling of Required

### ISSUE THREAD

**Issue by paulmortlock** [sam-ludlow/mame-ao#17]
Samples requierd

**Comment by sam-ludlow** [comment]
Hello thanks for that.

That was just a place holder until I fully implement samples in the next release.

https://github.com/sam-ludlow/mame-ao/commit/f60f71d3e098c8441504c824ada748e42489b8f8#diff-d1f752b8776b52c2c9dd60b51f20c7e08eff355ca4217c896ec50773370b5371L1015

**Comment by paulmortlock** [comment]
Also Compters is mis-spelled on the UI HTML
