### ISSUE TITLE
Compters is mis-spelled on the UI HTML

### ISSUE THREAD

**Issue by paulmortlock** [sam-ludlow/mame-ao#18]
![image](https://github.com/sam-ludlow/mame-ao/assets/7123294/017b1575-764d-4676-8cb7-a4e9985fcf77)

**Comment by paulmortlock** [comment]
Could not push the change how come?

**Comment by sam-ludlow** [comment]
Hello

I haven't really got a contributors plan yet. I won't be allowing commits directly to this repo.

What you need to is "fork" this repo make a branch, commit some changes, and if I like the look of it, I can pull your changes.

Cheers
Sam

**Comment by sam-ludlow** [comment]
Have a look here https://github.com/sam-ludlow/mame-ao/network
