### ISSUE TITLE
Unsure how or why this happens.

### ISSUE THREAD

**Issue by paulmortlock** [sam-ludlow/mame-ao#19]
![image](https://github.com/sam-ludlow/mame-ao/assets/7123294/8f4c5687-7fb7-4a4a-9a6d-3c0eefb0e5a6)

**Comment by sam-ludlow** [comment]
Hello

When passing software names to MAME if it exists in multiple software lists it guesses witch one to use.

I tested with: cpc6128p barb2

This exists in "cpc_cass" & "gx4000".

So double click on "cartridge"

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/7c5dbe7e-64ad-4b30-8f36-ea7511b353d5)

Then browse in the MAME UI to: mame-ao\0264\roms\gx4000\barb2

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/de071c0b-c3e4-4c1f-8303-c92e5f96f2b0)

When you double click the barb2.bin file it boots up.

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/d273356e-51c2-4e53-89b5-ab509a9f6a9a)

Cheers
Sam

**Comment by paulmortlock** [comment]
Gotcha thanks

**Comment by sam-ludlow** [comment]
Hello @paulmortlock 

This should work automatically now. I added passing the media type in 1.117

Cheers
Sam
