### ISSUE TITLE
Possible problem with large file downloads

### ISSUE THREAD

**Issue by paulmortlock** [sam-ludlow/mame-ao#24]
![image](https://github.com/sam-ludlow/mame-ao/assets/7123294/4469e709-3dc9-43c0-ac04-cca4b1574725)

**Comment by sam-ludlow** [comment]
Hello

Yes sometimes archive.org is slow or other network factors. That downloaded in about 10 mins when I tried.

I'll bump up the timeout.

Cheers
Sam

**Comment by sam-ludlow** [comment]
Made the timeout 6 hours

Fixed in https://github.com/sam-ludlow/mame-ao/releases/tag/1.88

Closing
