### ISSUE TITLE
Error with last version first execution

### ISSUE THREAD

**Issue by Aisflou** [sam-ludlow/mame-ao#25]
Hello, i just downloaded last version 1.87 run it, it started to do its things and then sttoped with an error, i tried executing it a second time and it thrown another different error... i paste the 2 logs with all the info.
[second run.txt](https://github.com/sam-ludlow/mame-ao/files/15220111/second.run.txt)
[first run.txt](https://github.com/sam-ludlow/mame-ao/files/15220113/first.run.txt)

**Comment by sam-ludlow** [comment]
Hello @Aisflou 

Looks like you ran out of memory. Then it left the intermediate files in a mess.

See the fix here: https://github.com/sam-ludlow/mame-ao/issues/16

Cheers
Sam

**Comment by Aisflou** [comment]
Hello, i just deleted the folder and started fresh, just in case. I have 16gb of ram in this test pc, ram sitted at 11.1gb consumption in total while mame-ao was running till i got the same "first" error again :( i didnt see that the ram got fully consumed, but i will make a clean reboot and try again later with anything more open. Thanks for the reply!

**Comment by paulmortlock** [comment]
Hi I also had this problem and Sam's reply should sort that out.

**Comment by Aisflou** [comment]
Hello again, running mame-ao with PC freshly rebooted did the trick. Dont know why it doesnt run when having more than 4gb of free ram, but now it runs perfectly. Thanks!
