### ISSUE TITLE
Running two at same time.

### ISSUE THREAD

**Issue by paulmortlock** [sam-ludlow/mame-ao#28]
Not that you need two going but if you try this happens.

![image](https://github.com/sam-ludlow/mame-ao/assets/7123294/49e97e04-84e4-4fcf-856c-d0e6925cf0e1)

https://stackoverflow.com/questions/93989/prevent-multiple-instances-of-a-given-app-in-net

**Comment by sam-ludlow** [comment]
Hello Paul yeah it kind of could if the web server listened on another port number, but defiantly not supported.

I may improve the error response.

Cheers Sam

**Comment by cewatkins** [comment]
The hack change I did just got a machine address ( for linux in this case ), but I dont have them handy and yes, if you do it remotely, you only get one a time and there's a number of reasons, I see why I think that's probably a good thing. but that's me.
Would be nice, it wasn't hard and I don't know the language.

**Comment by sam-ludlow** [comment]
Made the error a bit better.

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/36c18e50-b0c4-4e85-b518-29b56914fc21)

Fixed https://github.com/sam-ludlow/mame-ao/releases/tag/1.88

Closing
