### ISSUE TITLE
CHD download enhancement

### ISSUE THREAD

**Issue by billm23** [sam-ludlow/mame-ao#3]
I'm new to MAME and retro gaming in general so I was lucky to find this tool. It makes playing MAME games so easy! I was up and playing games in no time at all, so thank you for your hard work on this. As for the enhancement, because the download is one connection and internet archive throttles connections, CHD files can take a long time to download. It would be great if we could download the file manually using a download manager that supports multiple connections, save the file to the _temp directory under the actual file name and then the application could check if the file already exists and if it does process it then move on to checking/downloading the next file. When the file doesn't exist in the _temp directory it would download it.

So the steps would be...
1. Click on the image to start the downloading and installation process
2. If the file is large, copy the link within the console window (example: https://...archive.org/.../firefox.chd)
3. Ctrl+C to exit the application
4. Download the file and save it to the _TEMP directory 
5. Start the application
6. Click on the image to start the downloading and installation process
7. The application sees the file in the _TEMP directory and uses that one (example: firefox.chd)
8. The application finishes downloading any other required files and starts the game

I know this isn't an ideal solution, but it would be a huge time saver when downloading very large files.

Again thank you for your time and the effort you put into this tool.

**Comment by sam-ludlow** [comment]
Hello, thanks for you interest, I'm glad you find it easy, that's the plan.

Your request is noted I will be adding an import function pretty soon so you can feed it your own files.

Cheers Sam

**Comment by sam-ludlow** [comment]
Added in 1.48, drop your files in "C:\MameAo\_TEMP\IMPORT" then use the command ".import".

Cheers Sam

**Comment by billm23** [comment]
This is great! Thanks so much for your work!

**Comment by sam-ludlow** [comment]
Hello @billm23, out of interest how did you find MAME-AO, this repo?
