### ISSUE TITLE
Zip file question

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [sam-ludlow/mame-ao#31]
do you know if there is a way to compress the rom files to zip files to use up less storage space and enable more games.

**Comment by sam-ludlow** [comment]
Hello

There is currently no way to that.

The Hash Store with symbolic links method was chosen making it simple to account for ROMs and place then between MAME versions. Using ZIPs just adds too much complexity the downside being double the disk space for ROMs (CHD are already compressed).

Enabling symbolic links is about all you can do.

Cheers
Sam

**Comment by sam-ludlow** [comment]
Closing no plans to do this. Cheers
