### ISSUE TITLE
Issue With Area 51 ROM

### ISSUE THREAD

**Issue by Seahawkamafia** [sam-ludlow/mame-ao#32]
When i try to play the original Are 51 game this is what i get and of course it does not run the game due to the missing files. The sequel works just fine though. Is this something on my end or is this a global issue for everyone with this game? This is the first and only game ive had any issues getting to run thus far and ive been using MAME-ao for close to 6 months would now i would 

I have an unrelated question while I'm here how does one bind a mouse movement and mouse buttons in the same way they are default bound in sequel to area 51. I accidentally changed the default mouse button 1 to something else and for the life of me i cannot get any of the mouse buttons to rebind again, When i attempt to bind the button there is nothing registering when i click the mouse button but when i hit any other key it successfully binds to that specific keyboard key or button of my PS5 Dual Sense controller I use with many other games. Thanks for the help and hopefully you can do whatever needs to be done to fix Area 51 to work properly. 

AREA 51 Error When I attempt to run the game is below.....

                         #                                          Everything looks good to run MAME                                          #
#######################################################################################################################

Name:           area51
Description:    Area 51 (R3000)
Year:           1996
Manufacturer:   Atari Games
Status:         good
isbios:         no
isdevice:       no
ismechanical:   no
runnable:       yes

#######################################################################################################################
#                                                    Starting MAME                                                    #
#                    C:\Program Files\MAME Arcade Machine Emulator ver. 1.77 (64bit)\0265\mame.exe                    #
#                                                      area51                                                         #
#######################################################################################################################

2-c_area_51_hh.hh NOT FOUND (tried in area51)
2-c_area_51_hl.hl NOT FOUND (tried in area51)
2-c_area_51_lh.lh NOT FOUND (tried in area51)
2-c_area_51_ll.ll NOT FOUND (tried in area51)
jagwave.rom NOT FOUND (tried in area51)
area51.chd NOT FOUND (tried in area51)
Fatal error: Required files are missing, the machine cannot be run.

MAME Shell Exit BAD: 2

**Comment by sam-ludlow** [comment]
Hello @Seahawkamafia 

Are you running the latest version of MAME-AO? https://github.com/sam-ludlow/mame-ao/releases

I ran area51 on a clean install it worked fine. (It says a CHD missing but that's a bug it is not).

Your issue looks like its just the machine ROMs.

After you ensure MAME-AO is on the latest version can you supply the full output from the console, like so:

#######################################################################################################################
#                                               Remote command recieved                                               #
#                                                       area51                                                        #
#######################################################################################################################

#######################################################################################################################
#                                                  Asset Acquisition                                                  #
#######################################################################################################################

=======================================================================================================================
=                                                     Machine ROM                                                     =
=                                                       area51                                                        =
=                                              required machines: area51                                              =
=======================================================================================================================
Checking machine ROM: False     69da54ed6886e825156bbcc256e8d7abd4dc1ff8        area51  2-c_area_51_hh.hh
Checking machine ROM: False     9b4945bc04f8a73161638a2c5fa2fd84c6fd31b4        area51  2-c_area_51_hl.hl
Checking machine ROM: False     ae377a6803a4f7d1bbcc111725af121a3e82317d        area51  2-c_area_51_lh.lh
Checking machine ROM: False     4b5f45ee140b03a6be61475cae1c2dbef0f07457        area51  2-c_area_51_ll.ll
Checking machine ROM: False     58117e11fd6478c521fbd3fdbe157f39567552f0        area51  jagwave.rom
Downloading machine rom: 'area51' size:2.5 Megabytes (MiB) url:https://archive.org/download/mame-merged/mame-merged/area51.zip ........done
Download rate: 86.276s = 0.028 MiB/s
Extracting machine rom: 'area51', C:\Users\Admin\AppData\Local\Temp\tmp6E19.tmp.dir\archive.zip ......done
ROM Store Import: True 69da54ed6886e825156bbcc256e8d7abd4dc1ff8 machine rom: 'area51' \2-c_area_51_hh.hh
ROM Store Import: True 9b4945bc04f8a73161638a2c5fa2fd84c6fd31b4 machine rom: 'area51' \2-c_area_51_hl.hl
ROM Store Import: True ae377a6803a4f7d1bbcc111725af121a3e82317d machine rom: 'area51' \2-c_area_51_lh.lh
ROM Store Import: True 4b5f45ee140b03a6be61475cae1c2dbef0f07457 machine rom: 'area51' \2-c_area_51_ll.ll
ROM Store Import: True 58117e11fd6478c521fbd3fdbe157f39567552f0 machine rom: 'area51' \jagwave.rom
ROM Store Import: True 21864b4281b1ad17b2903e3aa294e4be74161e80 machine rom: 'area51' \area51a\136105-0000a.3k
ROM Store Import: True 90cf848a4195c51b505653cc2c74a3b9e3c851b8 machine rom: 'area51' \area51a\136105-0001a.3m
ROM Store Import: True dadc4be5a442dd4bd17385033056555e528ed994 machine rom: 'area51' \area51a\136105-0002a.3p
ROM Store Import: True 5d36cae792dd349faa77cd2d8018722a28ee55c1 machine rom: 'area51' \area51a\136105-0003a.3h
ROM Store Import: True cbed65463dd93eaf945750a9dc3a123d1c6bda42 machine rom: 'area51' \area51t\136105-0000-q_k.3k
ROM Store Import: True f95ef428be18adafae65e35f412eb03dcdaf7ed4 machine rom: 'area51' \area51t\136105-0001-q_m.3m
ROM Store Import: True 01a781b42b61279e09e0cb1d924e2a3e0df44591 machine rom: 'area51' \area51t\136105-0002-q_p.3p
ROM Store Import: True 9e96db5a4ff90800685a5b95f8d758d211d3b982 machine rom: 'area51' \area51t\136105-0003-q_h.3h
ROM Store Import: True a54552e3ac5c4f481ba4f2fc7d724534576fe76c machine rom: 'area51' \area51ta\136105-0000c.3k
ROM Store Import: True 2d9660f240b14481e8c46bc98713e9dc12035063 machine rom: 'area51' \area51ta\136105-0001c.3m
ROM Store Import: True 7c6c50372d45dca8929767241b092339f3bab4d2 machine rom: 'area51' \area51ta\136105-0002c.3p
ROM Store Import: True 39dabf6bf3dc6f717a587f362d040bfb332be9e1 machine rom: 'area51' \area51ta\136105-0003c.3h
Place machine ROM: True 69da54ed6886e825156bbcc256e8d7abd4dc1ff8        area51  2-c_area_51_hh.hh
Place machine ROM: True 9b4945bc04f8a73161638a2c5fa2fd84c6fd31b4        area51  2-c_area_51_hl.hl
Place machine ROM: True ae377a6803a4f7d1bbcc111725af121a3e82317d        area51  2-c_area_51_lh.lh
Place machine ROM: True 4b5f45ee140b03a6be61475cae1c2dbef0f07457        area51  2-c_area_51_ll.ll
Place machine ROM: True 58117e11fd6478c521fbd3fdbe157f39567552f0        area51  jagwave.rom
===================================================================================================================================================
=                                                                  Machine Disk                                                                   =
=                                                                     area51                                                                      =
===================================================================================================================================================
Checking machine Disk: False    3b303bc37e206a6d7339352c869f050d04186f11        area51  area51
Downloading area51/area51.chd size:475 Megabytes (MiB) url:https://archive.org/download/MAME_0.225_CHDs_merged/area51/area51.chd ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done
Download rate: 510.113s = 0.930 MiB/s
!!! Unexpected downloaded CHD SHA1. It's wrong in the source and will not work. expect:machine disk: 'area51/area51.chd' actual:3b303bc37e206a6d7339352c869f050d04186f11
Disk Store Import: True 3b303bc37e206a6d7339352c869f050d04186f11 area51/area51.chd
Place machine Disk: True        3b303bc37e206a6d7339352c869f050d04186f11        area51  area51

###################################################################################################################################################
#                                                               Machine Information                                                               #
#                                                                                                                                                 #
#                                                        Everything looks good to run MAME                                                        #
###################################################################################################################################################

Name:           area51
Description:    Area 51 (R3000)
Year:           1996
Manufacturer:   Atari Games
Status:         good
isbios:         no
isdevice:       no
ismechanical:   no
runnable:       yes

###################################################################################################################################################
#                                                                  Starting MAME                                                                  #
#                                                            C:\MAME-AO\0265\mame.exe                                                             #
#                                                                    area51                                                                       #
###################################################################################################################################################

MAME output:Average speed: 35.91% (16 seconds)

MAME Shell Exit OK.


MAME Shell (0265)>

**Comment by Seahawkamafia** [comment]
Hello, 
Here is what you requested. Thanks for the help.

1.87
'##::::'##::::'###::::'##::::'##:'########:::::::'###:::::'#######::
 ###::'###:::'## ##::: ###::'###: ##.....:::::::'## ##:::'##.... ##:
 ####'####::'##:. ##:: ####'####: ##:::::::::::'##:. ##:: ##:::: ##:
 ## ### ##:'##:::. ##: ## ### ##: ######::::::'##:::. ##: ##:::: ##:
 ##. #: ##: #########: ##. #: ##: ##...::::::: #########: ##:::: ##:
 ##:.:: ##: ##.... ##: ##:.:: ##: ##:::::::::: ##.... ##: ##:::: ##:
 ##:::: ##: ##:::: ##: ##:::: ##: ########:::: ##:::: ##:. #######::
..:::::..::..:::::..::..:::::..::........:::::..:::::..:::.......:::

       Please wait the first time it has to prepare the data

         The Web User Interface will pop up when ready

              See the README for more information
             https://github.com/sam-ludlow/mame-ao

#######################################################################################################################
#                                                    Initializing                                                     #
#######################################################################################################################
MameVersion: 0265
=======================================================================================================================
=                                                        MAME                                                         =
=                   https://github.com/mamedev/mame/releases/download/mame0265/mame0265b_64bit.exe                    =
=======================================================================================================================
Creating machine performance caches......done
Creating software performance caches......done
Getting all database SHA1s......done.
=======================================================================================================================
=                                                   Machine Genres                                                    =
=               https://raw.githubusercontent.com/AntoPISA/MAME_SupportFiles/main/catver.ini/catver.ini               =
=======================================================================================================================
Loading Genres......done
Version:        0.266
=======================================================================================================================
=                                                   Machine Samples                                                   =
=                 https://raw.githubusercontent.com/AntoPISA/MAME_Dats/main/MAME_dat/MAME_Samples.dat                 =
=======================================================================================================================
Version:        0.265

#######################################################################################################################
#                                         Remote Listener ready for commands                                          #
#                                               http://localhost:12380/                                               #
#                            e.g. http://localhost:12380/api/command?line=a2600 et -window                            #
#######################################################################################################################

#######################################################################################################################
#                                              Shell ready for commands                                               #
#######################################################################################################################

MAME Shell (0265)>
#######################################################################################################################
#                                               Remote command recieved                                               #
#                                                       area51                                                        #
#######################################################################################################################

#######################################################################################################################
#                                                  Asset Acquisition                                                  #
#######################################################################################################################

=======================================================================================================================
=                                                     Machine ROM                                                     =
=                                                       area51                                                        =
=                                              required machines: area51                                              =
=======================================================================================================================
Checking machine ROM: True      69da54ed6886e825156bbcc256e8d7abd4dc1ff8        area51  2-c_area_51_hh.hh
Checking machine ROM: True      9b4945bc04f8a73161638a2c5fa2fd84c6fd31b4        area51  2-c_area_51_hl.hl
Checking machine ROM: True      ae377a6803a4f7d1bbcc111725af121a3e82317d        area51  2-c_area_51_lh.lh
Checking machine ROM: True      4b5f45ee140b03a6be61475cae1c2dbef0f07457        area51  2-c_area_51_ll.ll
Checking machine ROM: True      58117e11fd6478c521fbd3fdbe157f39567552f0        area51  jagwave.rom
Place machine ROM: True 69da54ed6886e825156bbcc256e8d7abd4dc1ff8        area51  2-c_area_51_hh.hh
Place machine ROM: True 9b4945bc04f8a73161638a2c5fa2fd84c6fd31b4        area51  2-c_area_51_hl.hl
Place machine ROM: True ae377a6803a4f7d1bbcc111725af121a3e82317d        area51  2-c_area_51_lh.lh
Place machine ROM: True 4b5f45ee140b03a6be61475cae1c2dbef0f07457        area51  2-c_area_51_ll.ll
Place machine ROM: True 58117e11fd6478c521fbd3fdbe157f39567552f0        area51  jagwave.rom
=======================================================================================================================
=                                                    Machine Disk                                                     =
=                                                       area51                                                        =
=======================================================================================================================
Checking machine Disk: True     3b303bc37e206a6d7339352c869f050d04186f11        area51  area51
Place machine Disk: True        3b303bc37e206a6d7339352c869f050d04186f11        area51  area51

#######################################################################################################################
#                                                 Machine Information                                                 #
#                                                                                                                     #
#                                          Everything looks good to run MAME                                          #
#######################################################################################################################

Name:           area51
Description:    Area 51 (R3000)
Year:           1996
Manufacturer:   Atari Games
Status:         good
isbios:         no
isdevice:       no
ismechanical:   no
runnable:       yes

#######################################################################################################################
#                                                    Starting MAME                                                    #
#                    C:\Program Files\MAME Arcade Machine Emulator ver. 1.77 (64bit)\0265\mame.exe                    #
#                                                      area51                                                         #
#######################################################################################################################

2-c_area_51_hh.hh NOT FOUND (tried in area51)
2-c_area_51_hl.hl NOT FOUND (tried in area51)
2-c_area_51_lh.lh NOT FOUND (tried in area51)
2-c_area_51_ll.ll NOT FOUND (tried in area51)
jagwave.rom NOT FOUND (tried in area51)
area51.chd NOT FOUND (tried in area51)
Fatal error: Required files are missing, the machine cannot be run.

MAME Shell Exit BAD: 2

**Comment by Seahawkamafia** [comment]
i am so sorry i do not why it enlarged parts of the copy paste, it was all the same size when i copied and when i pasted it but as soon as i hit submit or comment or whatever it enlarged a portion of the message for some odd reason. i apologize. that was not intended.

**Comment by sam-ludlow** [comment]
No worries you want to put 3 back-ticks above and below it. I've edited it for you go, if you go to edit you can see.

Hmmm it looks like mame-ao is reporting it placed the files OK but mame itself don't find them.

Have you been messing with the rom location config?

**Comment by sam-ludlow** [comment]
My output looks the sane as yours suggesting all files are in place.

What you got in: C:\My Program Filesw\MAME Arcade Machine Emulator ver. 1.77 (64bit)\0265\roms\area51

this is all it needs to boot

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/d0a0cf6a-89fc-44ec-b052-4d519b6263a2)

If those files are there then it must be mame rom location config.

Also "C:\Program Files" probably isn't the best place the permissions can be restrictive.

**Comment by Seahawkamafia** [comment]
Hey, OK ill uninstall it and re install in its own directory but the part way down at the bottom of my screen shot says multiple files are missing and when I checked it is right there are only like 3 or 4 symbolic links in the folder for area 51 yet according to the error message there are several files that are missing.  Does that also say the same thing for you when you try and use area51? Ill update you after I remove and install in its own directory and see if that changes anything for me. I don't have a dedicated emulator setup or cabinet or anything fancy like that im just using my HP "Gaming" PC and I emphasize the quotes heavily. LOL  Anyways, knowing that do you suggest I install it its own directory on the C Drive? I do have several other drives installed that have a decent amount of space on them if that would work better....

**Comment by sam-ludlow** [comment]
If you want to start a clean install just copy the old _STORE & _STORE_DISK directories to the new.

So you don;t have to download stuff again, everything else will be created fresh.

**Comment by sam-ludlow** [comment]
Hello

This Area 51 issue is a weird one, you're not an alien abductee or something are you?

I have added asset placing reports, please update to the latest version of MAME-AO. Then switch it on here.

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/d0ed1690-3857-41d2-8f38-0c792ab504e4)

Then run "area51" and attach the report from the "_REPORTS" directory here.

This is what mine looks like. (You have to ZIP it)

[2024-06-21T13-14-57_Place Assets area51.zip](https://github.com/user-attachments/files/15927667/2024-06-21T13-14-57_Place.Assets.area51.zip)

Cheers
Sam

**Comment by Seahawkamafia** [comment]
Hey Sam,
So I actually ended up getting it to work. When I originally was trying to play the game I just used the search bar and only one version of the area 51 game popped up and then a sequel I believe popped up as well. Well I was looking for other games to play and I ended up just using the genres menu and found my way to the games under the Gun listing and accidentally ran into the area51 games which  had several listed. When I attempted to play from those listed games everything worked fine and I was able to play the game all the way thru without any issues. Thanks again for your help with everything. It was much appreciated. I did have one other quick question. How do I use my mouse to play the shooting games with a crosshair, right now I don't own a gun style controller so im having to use my DualSense controller which works just fine but it isn't quite as easy to aim and I know I can do better in the game if I was able to use my mouse to move the crosshair and mouse button to shoot. Any help or a push in a direction for me to look would help greatly. Ive searched youtube and such but all the videos deal with the vanilla version of MAME and I cant seem to find a way to access the same UI Menus as it shows in the videos when using the MAME-UI because they are the ones you access prior to entering a game which I believe you so kindly have done all the configuration for us as part of your MAME-AO build, from my limited knowledge of how all this works I assume this to be the case but I could very wrong as well as im not well versed in MAME or writing code and programming software. Just wanted to mention that I am in no way complaining about not having the access to those menus as I actually like your build quite a lot better as its easier to get in and enjoy some games without having to configure everything ourselves and who knows how messed up id have things if I were to be required to do all the setting up myself. As a small side note I am able to hit the TAB key and access the in game menu once I have booted a game up but I cant seem to figure out how to map my mouse movements within said menus or im doing something incorrect. Either way any info you could bestow upon me would be huge help as ive not been able to find much in the way of help on that subject anywhere online.
Also is there a way to set the controls globally so I don't have to assign the inputs to my controller instead of the keyboard each time I play a game that I have not played before by chance? Not a big issue just a convenience type of question.  Sorry to take up so much of your time. I appreciate all your help everything has been working flawlessly and have not had any other issues other than the area 51 thing that I ended up working out anyways so kudos on such a cool thing you've provided the emulation community.

PS
I don't think I am an alien abductee, but im guessing if I were they would have wiped my memory of it so I wouldn't rememeber it so I dont go and attempt to ruin their plans for global domination, that's at least what id like to think cause im rather certain id prefer to not remember aliens doing experiments or whatever it is aliens do to their abductees! LOL!

Have a great day!
James

**Comment by sam-ludlow** [comment]
Hello @Seahawkamafia 

Glad you got Area 51 working went round the houses a bit but no worries.

Re. mouse control - this a general MAME query, pretty sure I had it working myself a while back with a mouse I'd have to look it up myself. I'll have a play at some point if I remember and let you know here.

Closing ticket.

Cheers
Sam
