### ISSUE TITLE
New mame-ao alternatives for other emulators

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [sam-ludlow/mame-ao#36]
I would like to boot up a ps1 or ps2 game with the properties as mame-ao to run games easily that are easily downloaded and managed in some way. the name could probably be ps1-ao and ps2-ao or ducksta-ao and pcsx2-ao. maybe also include dreamcast, naomi, atomiswave and system sp flycast-ao for that. gamecube, wii, and triforce for dolphin-ao.

https://archive.org/download/chd_psx/CHD-PSX-USA/
https://archive.org/download/chd_psx_eur/CHD-PSX-EUR/
https://archive.org/download/chd_psx_jap/CHD-PSX-JAP/

https://archive.org/download/chd_dc/CHD-Dreamcast/

https://archive.org/download/rvz-gc-usa-redump/RVZ-GC-USA-REDUMP/
https://archive.org/download/rvz-gc-europe-redump/RVZ-GC-EUROPE-REDUMP/
https://archive.org/download/rvz-gc-asia-redump/RVZ-GC-ASIA-REDUMP/

and such.

**Comment by sam-ludlow** [comment]
Well that's a tall order. I'd like to support other emulators but that's not happening any time soon.

**Comment by paulmortlock** [comment]
Aren't PS1 and Ps2 games runnable with MAME already so can any of these be launched and downloaded using current mame-ao maybe these sources can be added? Will they then appear in the UI Sam?

**Comment by Iamthebestintheworld222** [comment]
That is true, but ps2 on mame is only the bios and ps1 on there is a bit limited and you can't play regional differences for games like r-type delta, final fantasy vii or xevious 3d/g+

**Comment by paulmortlock** [comment]
Aha right so would need to use duckstation or retroarch. hmmm or dolphin you're quite right and this is mame oriented.

**Comment by paulmortlock** [comment]
I would be keen on support for other emulators too. What would need amending to make a dolphin-ao or merge into mame-ao and use the archive.org sources. Maybe change to multi-emu-ao.

**Comment by sam-ludlow** [comment]
Adding other emulators is a long way down the road.

Closing ticket
