### ISSUE TITLE
Add Installer

### ISSUE THREAD

**Issue by paulmortlock** [sam-ludlow/mame-ao#38]
An installer would be useful and possibly bypass the windows defender warning.

**Comment by sam-ludlow** [comment]
Agreed make it real easy for novices.

Installers are always more messy to make than you'd think, but I've done one before.

To get rid of the defender notice I think you need to build signed binaries in git or something, have to look into that.

Other than using proper installers I was thinking of a single exe installer that just downloads and places the files. Some users will probably struggle just extracting a ZIP.

**Comment by sam-ludlow** [comment]
Closing this, maybe one day, but no plans at all currently.
