### ISSUE TITLE
Genres not showing machines correctly

### ISSUE THREAD

**Issue by sam-ludlow** [sam-ludlow/mame-ao#39]
I noticed when browsing through Genres it wasn't showing all the machines.

The fix is delete `_machine.sqlite` from inside the MAME version directory and let it get recreated.

Root cause I'm not that sure. MAME-AO will update the DB with new genre data when `catver.ini` gets a version bump.

I'm guessing the file changed on GitHub without a version bump?

The in-memory genre data is parsed each time MAME-AO starts and the DB only on the version bump. As parsing creates internal IDs they may have become out of sync with the IDs in the DB.

Not sure will have to look into it.

**Comment by sam-ludlow** [comment]
Pretty sure it was that

https://github.com/AntoPISA/MAME_SupportFiles/commit/0c9f81e1dc82c3faedc6623237f8a3b434761658

Bunch of changes here and the top comment that MAME-AO parses the version from did not change.

I changed the metadata caching to download fresh if its over 3 hours old (not on version bumps).

So the genre data was downloaded and the DB updated, then later genre data changed on GitHub the cache refreshed it as its the same version the DB was left alone BUT each time MAME-AO starts it parses the file again creating internal IDs. Oh dear now these don't match the DB.

I should look at that.

**Comment by sam-ludlow** [comment]
Use a hash of the file rather then the version, dummy.

**Comment by paulmortlock** [comment]
Very interesting can you show an example of what was missing please.

**Comment by sam-ludlow** [comment]
It was a shambles, fixed in 1.90

**Comment by paulmortlock** [comment]
I extracted to my current mam-ao and get this initially.

![image](https://github.com/sam-ludlow/mame-ao/assets/7123294/fb39e267-7c0a-4f2c-9398-22b9938b009f)

**Comment by paulmortlock** [comment]
![image](https://github.com/sam-ludlow/mame-ao/assets/7123294/8fc12a91-ed8e-44ad-817e-0638ff209b90)

**Comment by sam-ludlow** [comment]
Hmm we got another issue for this please talk about it there.

**Comment by sam-ludlow** [comment]
Closing ticket Genre bug looks fixed.
