### ISSUE TITLE
CFG file to easy config

### ISSUE THREAD

**Issue by leallindao** [sam-ludlow/mame-ao#4]
- Hello, I would like to congratulate you on the software! Excellent.
- Favorite added in the latest version! - OK
- Configuration file (cfg or ini) for settings, such as removing symbolic links, how to do it?
- Configuration file (cfg or ini) for settings, such as changing archive.org to another mirror - archive.org is often overloaded. (For example, I downloaded the .torrent file and created a local web server with the name archive.org)
- When updating to a new version of MAME, it would be interesting to have an option to migrate the MAME configuration files to the new folder.

**Comment by sam-ludlow** [comment]
Hello, thanks for the feedback.

- Software List favourites coming soon
- Configuration symbolic links? You configure this in the OS see readme.
- Configuration other sources - Maybe, you can use the .import function for stuff already downloaded.
- migrate the MAME configuration - Yes I've been thinking about that.

Exactly what config files do you want to migrate? mame.ini and cfg directory anything else? Just copy them?

Cheers
Sam

**Comment by leallindao** [comment]
Where is readme ?
How can i get ?

**Comment by sam-ludlow** [comment]
README is here https://github.com/sam-ludlow/mame-ao
see.
Symbolic Links - Save disk space

**Comment by sam-ludlow** [comment]
Not entirely sure if migration of config is such a good idea?

Occasionally breaking changes do occur between MAME versions, maybe not break but result in unexpected behaviour, going from the odd thread I've read.

Maybe a command to do it if the user wants with a disclaimer?

But doing it automatically may break stuff for casual users.

**Comment by sam-ludlow** [comment]
Closing

May add new config features in the future.
