### ISSUE TITLE
404 error 

### ISSUE THREAD

**Issue by cewatkins** [sam-ludlow/mame-ao#42]
Downloading MAME binaries https://github.com/mamedev/mame/releases/download/mameROM S/mameROM Sb_64bit.exe ...
!!! FATAL ERROR: The remote server returned an error: (404) Not Found.

Probably part of last bug?

**Comment by sam-ludlow** [comment]
Hello yes that was fixed here https://github.com/sam-ludlow/mame-ao/issues/40

Download the latest https://github.com/sam-ludlow/mame-ao/releases/latest
