### ISSUE TITLE
wine breaks with update.

### ISSUE THREAD

**Issue by cewatkins** [sam-ludlow/mame-ao#45]
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"edgeupdate" failed to start: 2
0024:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed

So, copying the windows install doesn't work either, I got it to install in vm, but where it
did work the upgrade breaks it. 
Know ya don't support wine, I suppose I could go rip out that new stuff.
But, the installer suggestion might fix this sort of thing.
Although, the binary is pretty looking the way it is in cli..

**Comment by sam-ludlow** [comment]
Hello @cewatkins 

Hmm not sure what would break WINE I've not done anything except logic changes recently.

1.93
https://github.com/sam-ludlow/mame-ao/compare/1.92...1.93

1.92
https://github.com/sam-ludlow/mame-ao/compare/1.91...1.92

I need to setup a VM with WINE on myself, never got round to it.

I see "edgeupdate" in your error, is there a problem when MAME-AO starts the UI in the default browser?

Cheers
Sam

**Comment by sam-ludlow** [comment]
@cewatkins 

I'm no Linux novice but I've never ran WINE before and don't use a Linux box currently.

Any recommendations? Is there a WINE friendly distro or should a just install Ubuntu and put WINE on?

Cheers
Sam

**Comment by cewatkins** [comment]
Ok, so, I'm not rulling the wine environment out.  And, I know what you mean about logical choices, I've loaded the code in a vm, I made it so it broadcasted to 0.0.0.0, so I could choose multi-user like from different playforms out of the web..  OK, so, This edge-update thing, may be wine.  Because basically, I just see the mame-ao ascii and the sucker started but in the library's or something it seems like it's trying to update edge..  NOW, This being said, A NUMBER of programs get hosed by edgeupdate not being fixed in wine, so it's a  wider problem. One of the library calls is probably trying to update edge, so i dunno if you point that at wine, or m$'s usage, I'd have to load the debugger and see where it goes to do it..  So, I also am on manjaro now so, the base wine changes.  So, don't know it indeed may not be mame-ao.  However, I do this because it's good notes, in case people try and go DANG! cause it works nicely in wine.  And in fact install mono makes it not work..  Love the product! I see you've added a bunch of stuff..  Also, I extracted the entire install, copied it into wine and it didn't work. so, anyway, hope that makes sense.

**Comment by sam-ludlow** [comment]
I installed Ubuntu on a real PC tried to install Wine it gave me load of grief. So I think I'll try again with a distro with Wine built in.

Before I do that I wouldn't mind seeing how well it works with just Mono and maybe have a go with recent .net (not 4.8).

**Comment by sam-ludlow** [comment]
For lolz I had it running with monodevelop.

But it would need wiring up for Linux MAME binaries.

![image](https://github.com/user-attachments/assets/85c33e4d-bb7f-444c-8455-def08524bdff)

**Comment by sam-ludlow** [comment]
Closing, I have to play more with Linux but don't have the time. MAME-AO remains officially Windows only for now.
