### ISSUE TITLE
archive.org 503 Server Unavailable

### ISSUE THREAD

**Issue by paulmortlock** [sam-ludlow/mame-ao#54]
![image](https://github.com/user-attachments/assets/e0f78b3c-c966-486a-bcbb-5a0d2a25768b)

**Comment by paulmortlock** [comment]
oh dear what's happened to internet archive .org

**Comment by paulmortlock** [comment]
> oh dear what's happened to internet archive .org

https://blog.archive.org/2024/10/18/internet-archive-services-update-2024-10-17/

**Comment by paulmortlock** [comment]
what if we use https://github.com/alanmcgovern/monotorrent and scrape the magnet links from pleasuredome https://pleasuredome.github.io/pleasuredome/mame/

**Comment by sam-ludlow** [comment]
Hello @paulmortlock 

Yes archive.org has been attacked. I hope they should be back up soon.

The PD torrents are something I have considered and that monotorrent library looks like it may be the way to go.

Cheers
Sam

**Comment by paulmortlock** [comment]
I have branched and am working on monotorrent using the magnet links from pleasuredome and so far does start downloading the files.

**Comment by sam-ludlow** [comment]
Looks like archive.org is working for anonymous access but you can't log in yet.

![image](https://github.com/user-attachments/assets/c91801c4-30a2-402c-b14e-d0827d826813)

MAME-AO still wont work until you can login.

**Comment by InitialXKO** [comment]
![image](https://github.com/user-attachments/assets/2ea80d32-7566-418b-b02b-254a46f73529)

**Comment by InitialXKO** [comment]
Looks like archive.org is down again.

**Comment by paulmortlock** [comment]
Am working on something that can use the magnetlinks and run mame-ao any ideas welcome.

![image](https://github.com/user-attachments/assets/b879ebe0-5af1-4e66-b8fe-f010535e57e2)

**Comment by sam-ludlow** [comment]
Hello @paulmortlock I've not had a chance to look at your work yet. But will do soon.

**Comment by sam-ludlow** [comment]
Lets keep this thread on topic for people arriving wondering what's happened to archive.org
@paulmortlock use this for BT comments https://github.com/sam-ludlow/mame-ao/issues/60

**Comment by paulmortlock** [comment]
![image](https://github.com/user-attachments/assets/9220d42c-29cc-4c35-b11e-adb29e44b56b)

**Comment by sam-ludlow** [comment]
Yeah still not allowing logins, lets hope it gets sorted soon.

**Comment by anonimo82** [comment]
Hello. I made it to login yesterday, please, can you check?

**Comment by sam-ludlow** [comment]
Hello archive.org is now allowing logins.

But MAME-AO is not working with it, maybe they changed something to do with auth.

WORKAROUND:

Log into archive.org

Go here https://archive.org/download/mame-merged/mame-merged/005.zip/

Hit F12/network Grab the cookie and paste into this file.

`D:\MAME AO\_TEMP\CACHE\archive.org-auth-cookie.txt`

![image](https://github.com/user-attachments/assets/c31a6c6f-d051-4cb0-8b16-1c0fd415f0a2)

That should get you going.

I will fix properly later.

Cheers
Sam

**Comment by anonimo82** [comment]
Which browser are you using?

**Comment by sam-ludlow** [comment]
Hello @anonimo82 I'm using Edge.

**Comment by anonimo82** [comment]
I made it with the cookie, but I can't download mame-ao and mame, the first times out, the latter never gets done and I have to halt it.
I tried to manually download the json files, but I don't know where should I put them.
Where?

Thanks for any help.

**Comment by sam-ludlow** [comment]
I just tested a totally clean MAME-AO 1.97 with just the auth cookie.

It worked fine for `mrdo` and `a2600 et`

**Comment by anonimo82** [comment]
Please, use code tags

**Comment by cewatkins** [comment]
i had to do this.. sed -i 's/\r//g' filename && tr -d '\n' < filename > new_filename
but i'm using wine. oddly though i saved with notepad and got the same stuff, but i'm also cut and pasting accross platforms so.. anyway..  yeehaw! launched!

**Comment by anonimo82** [comment]
Please, which file did you exactly did that sed stuff?
I'm using wine too, so I'm very interested!
Thanks in advance for any help. @cewatkins

**Comment by sam-ludlow** [comment]
The auth cookie workaround

!!! must only be one line in the file

![image](https://github.com/user-attachments/assets/dbfc880f-f13c-424d-8675-6169f6257164)

**Comment by sam-ludlow** [comment]
Sorry should have mentioned that before.

**Comment by cewatkins** [comment]
> Please, which file did you exactly did that sed stuff? I'm using wine too, so I'm very interested! Thanks in advance for any help. @cewatkins P.S.: If you can, please, provide detailed info

Ok, yes, so it is what sam said, now I tried cut and paste, both browsers, notepad, nothing.
Then if you sed -i 's/\r//g' archive.org-auth-cookie.txt && tr -d '\n' < archive.org-auth-cookie.txt > archive.org-auth-cookie.txt1
then copy the .txt1 file over the .txt, it removes /n/r's that the editor puts back in
and somehow the api test does't like that, as sam-ludlow it must be one line, which I got, but as I cmp'd them, it complained of EOF too.  So. Also copy value out of the debugger helps a bit.
Now I did not edit the string so I don't  know what the %2 note above is.
when you have a non-authed cookie, it's simple enough, it doesn't complain that way but it has spaces too.. 
So, cookie jar management.. haha. I said .jar  
Cookie Monster..

Also, to get it to make the .txt file in the first place i logged in with blank user name and passwords or it isn't there.

**Comment by anonimo82** [comment]
Thanks so much for sharing. But I'm stuck at downloading mame-ao and mame from github, the cookie already works.

**Comment by sam-ludlow** [comment]
MAME-AO has been fixed for the new archive.org auth in 1.98

https://github.com/sam-ludlow/mame-ao/releases

If you have any problems delete this file and restart MAME-AO

`MAME AO\_TEMP\CACHE\archive.org-auth-cookie.txt`

Cheers
Sam

**Comment by sam-ludlow** [comment]
Hello @cewatkins 

As MAME-AO caches the GitHub metadata for 3 hours you probably just caught it wrong.

https://github.com/sam-ludlow/mame-ao/blob/026ca2c37cfda2092c39a147d499627eec80ec9a/source/Tools.cs#L298

Cheers
Sam

**Comment by sam-ludlow** [comment]
Closing archive.org has settled down now and MAME-AO is using the new archive.org authentication.

**Comment by anonimo82** [comment]
Yep, thanks a lot
