### ISSUE TITLE
FATAL ERROR: 0x80004005 network path not found

### ISSUE THREAD

**Issue by prodev-zz** [sam-ludlow/mame-ao#6]
Hello Sam,

When running mame-ao.exe I get the following error:

_
#######################################################################################################################
#                                       Welcome to Spludlow MAME-AO Shell V1.57                                       #
#                                        https://github.com/sam-ludlow/mame-ao                                        #
#######################################################################################################################

Give it a moment the first time you run

Usage: type the MAME machine name and press enter e.g. "mrdo"
       or a CHD e.g. "gauntleg"
       or with MAME arguments e.g. "mrdo -window"

SL usage: type the MAME machine name and the software name and press enter e.g. "a2600 et"
       or a CHD e.g. "cdimono1 aidsawar" (Note: Not all CHD SLs are not currently available)
       or with MAME arguments e.g. "a2600 et -window"

Use dot to run mame without a machine e.g. ".", or with paramters ". -window"
If you have alreay loaded a machine (in current MAME version) you can use the MAME UI, filter on avaialable.

List saved state: ".list".

You can start a particular version of MAME with the command ".VVVV" where V is the version e.g. ".0252" or pass arguments e.g. ".0252 mrdo -window".

WARNING: Large downloads like CHD will take a while, each dot represents 1 MiB (about a floppy disk) you do the maths.

#######################################################################################################################
#                                                    Initializing                                                     #
#######################################################################################################################

Data Directory: D:\MAME

Symbolic Links Enabled: False
!!! You can save a lot of disk space by enabling symbolic links, see the README.

=======================================================================================================================
=                                             Prepare source: MachineRom                                              =
=======================================================================================================================
Loading MachineRom metadata JSON D:\MAME\_METADATA\MachineRom_mame-merged.json ......done.
Title:  MAME 0.256 ROM Set (Merged)
Version:        0256
=======================================================================================================================
=                                             Prepare source: MachineDisk                                             =
=======================================================================================================================
Loading MachineDisk metadata JSON D:\MAME\_METADATA\MachineDisk_MAME_0.225_CHDs_merged.json ......done.
Title:  MAME 0.255 CHDs (merged)
Version:        0255
!!! MachineDisk on archive.org version mismatch, expected:0256 got:0255. You may have problems.
=======================================================================================================================
=                                             Prepare source: SoftwareRom                                             =
=======================================================================================================================
Loading SoftwareRom metadata JSON D:\MAME\_METADATA\SoftwareRom_mame-sl.json ......done.
Title:  MAME SL 0.256 (Merged) - No CHD
Version:        0256
=======================================================================================================================
=                                            Prepare source: SoftwareDisk                                             =
=======================================================================================================================
Loading SoftwareDisk metadata JSON D:\MAME\_METADATA\SoftwareDisk_mame-sl-chd-cdi.json ......done.
Title:  MAME SL CHD - cdi
Version:        MAME SL CHD - cdi
Loading SoftwareDisk metadata JSON D:\MAME\_METADATA\SoftwareDisk_mame-sl-chd-neocd.json ......done.
Title:  MAME SL CHD - neocd
Version:        MAME SL CHD - neocd
Loading SoftwareDisk metadata JSON D:\MAME\_METADATA\SoftwareDisk_mame-sl-chd-pcecd.json ......done.
Title:  MAME SL CHD - pcecd
Version:        MAME SL CHD - pcecd
Loading SoftwareDisk metadata JSON D:\MAME\_METADATA\SoftwareDisk_mame-software-list-chds-2.json ......done.
Title:  mame-software-list-chds
Version:        mame-software-list-chds
=======================================================================================================================
=                                                        MAME                                                         =
=                   https://github.com/mamedev/mame/releases/download/mame0256/mame0256b_64bit.exe                    =
=======================================================================================================================
Creating machine performance caches......done
Creating software performance caches......done
Getting all SHA1s......done.

!!! FATAL ERROR: Det går inte att hitta nätverksplatsen. Information om hur nätverksfel kan felsökas finns i Windows Hjälp

System.Net.HttpListenerException (0x80004005): Det går inte att hitta nätverksplatsen. Information om hur nätverksfel kan felsökas finns i Windows Hjälp
   vid System.Net.HttpListener.AddAllPrefixes()
   vid System.Net.HttpListener.Start()
   vid Spludlow.MameAO.WebServer.StartListener()
   vid Spludlow.MameAO.MameAOProcessor.Shell()
   vid Spludlow.MameAO.MameAOProcessor.Run()

If you want to submit an error report please copy and paste the text from here.
Select All (Ctrl+A) -> Copy (Ctrl+C) -> notepad -> paste (Ctrl+V)

Report issues here https://github.com/sam-ludlow/mame-ao/issues

Press any key to continue, program has crashed and will exit.
_

I have checked that all the prerequisites (correct version of .net and so on) are installed and have tried running both as a normal user and as an administrator. I am unsure of what to try next!

Regards,
Anders

**Comment by sam-ludlow** [comment]
Hello Anders

Thanks for the bug report.

Looks like it had an issue starting the web server. It uses http://127.0.0.1:12380/

So IPv4 localhost and port 12380.

Does your machine use IPv6 only network stack?

Look in network settings-> Adapter (whatever) -> Edit IP settings -> Is IPv4 switched off? Try switching it on, see if that helps.

I should probably use "localhost" this should always resolve. And do some tests with IPv6.

Cheers
Sam

**Comment by sam-ludlow** [comment]
Hello Anders I've changed it in 1.58 to use "localhost".

Did that fix it? (forget about your network settings for now).

If it did then I expect your machine is IPv6 only? Can you confirm this out of interest?

Cheers Sam

**Comment by sam-ludlow** [comment]
Closing, I'm pretty sure localhost will fix this issue.

I didn't test on a IPv6 only box, but it seems to use IPv6 with localhost anyway.
