### ISSUE TITLE
Fatal Error 400

### ISSUE THREAD

**Issue by Pep0950** [sam-ludlow/mame-ao#61]
!!! FATAL ERROR: Response status code does not indicate success: 400 (Bad Request).

System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at Spludlow.MameAO.ArchiveOrgAuth.GetCookie()
   at Spludlow.MameAO.MameAOProcessor.Initialize()
   at Spludlow.MameAO.MameAOProcessor.Run()

**Comment by sam-ludlow** [comment]
Hello @Pep0950 

This is down to archive.org still not accepting logins after they where attacked.

Hopefully they will get it working soon.

See here

https://github.com/sam-ludlow/mame-ao/issues/54

Cheers
Sam

**Comment by Pep0950** [comment]
Just wanted to be aware, thank you.

**Comment by sam-ludlow** [comment]
Closing see here https://github.com/sam-ludlow/mame-ao/issues/54
