### ISSUE TITLE
!!! FATAL ERROR: Response status code does not indicate success: 400 (Bad Request).

### ISSUE THREAD

**Issue by josejuanmartinez** [sam-ludlow/mame-ao#65]
Something seems to have changed in the log in process in archive.org? This is what I get when logging in to mame-ao:
```
Enter your Archive.org username:
jjmcarrascosa@gmail.com
Enter your Archive.org password:
XXXXXXXX

!!! FATAL ERROR: Response status code does not indicate success: 400 (Bad Request).

System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at Spludlow.MameAO.ArchiveOrgAuth.GetCookie()
   at Spludlow.MameAO.MameAOProcessor.Initialize()
   at Spludlow.MameAO.MameAOProcessor.Run()
```

**Comment by sam-ludlow** [comment]
Hello

I'm seeing different behaviour. I can enter good or bad creds and MAME-AO continues just fails with 403 at asset download. This needs looking at, it should fail with the bad creds.

It is working properly with correct creds.

You on the latest? https://github.com/sam-ludlow/mame-ao/releases/latest

Try deleting the file `MAME AO\_TEMP\CACHE\archive.org-auth-cookie.txt` and restart MAME-AO.

Cheers
Sam

**Comment by josejuanmartinez** [comment]
Thank you for answering! I deleted 1.97 and download 1.98 and it worked!
