### ISSUE TITLE
nm-002 is not found to play "taiko2"

### ISSUE THREAD

**Issue by VictorXcraft** [sam-ludlow/mame-ao#8]
![image](https://github.com/sam-ludlow/mame-ao/assets/81340759/df1490bb-4457-4d11-b20e-6846418a7272)

**Comment by sam-ludlow** [comment]
Hello thanks for the feedback.

This is wrong in the source, not in MAME-AO.

The workaround is download the file manually from here:

https://archive.org/download/MAME_0.225_CHDs_merged/taiko2/tk-21.chd

Then run the command:

.import C:\SomeDirWithCHD

You can now run "taiko2", looks like a grand machine.

It is the correct file (SHA1) but is named wrong. see https://mame.spludlow.co.uk/Machine.aspx?name=taiko2

It should be named "nm-002.chd".

Cheers Sam

**Comment by sam-ludlow** [comment]
I have added a "Source Exists Machine Disk" report in 1.59

I could only spot 3 machines that where bad in the source 1 of them being "taiko2" so bad luck.

Machine	RomOf	Merge	Description	Name	SHA1
popn1			Pop'n Music 1 (ver TA-A, HDD 1.01)	803_ta_hdd	be833a3c0f1e5953271fa7d8d6e81211fbe9710f
popn1k	popn1	803_ta_hdd	Pop'n Music 1 (ver KA-A, HDD 1.01)	803kaa11	be833a3c0f1e5953271fa7d8d6e81211fbe9710f
taiko2			Taiko no Tatsujin 2 (Japan, TK21 Ver.C)	nm-002	cede127f3d87f894ccaa1d77c8b279f209f6a8e4

I will attempt to contact the source to fix this.

Cheers Sam

**Comment by sam-ludlow** [comment]
Also be nice if the .import command accepted a URL or path to a single file (not just a directory)

**Comment by sam-ludlow** [comment]
Closing

Ran source exists report and they (not including all software disk) look like they are in present in the source now.
