### ISSUE TITLE
Unable to start MAME-AO properly

### ISSUE THREAD

**Issue by VictorXcraft** [sam-ludlow/mame-ao#9]
![image](https://github.com/sam-ludlow/mame-ao/assets/81340759/afe30e94-d26c-45d6-91f2-d53692eb7fb4)

**Comment by sam-ludlow** [comment]
Hello, I suspect this is due to network issues or archive.org is running slow.

Just retry later,

I plan on improving handling of network issues at some point,

Cheers
Sam

**Comment by mcbruce76** [comment]
#######################################################################################################################
#                                       Welcome to Spludlow MAME-AO Shell V1.62                                       #
#                                        https://github.com/sam-ludlow/mame-ao                                        #
#######################################################################################################################

Give it a moment the first time you run

Usage: type the MAME machine name and press enter e.g. "mrdo"
       or a CHD e.g. "gauntleg"
       or with MAME arguments e.g. "mrdo -window"

SL usage: type the MAME machine name and the software name and press enter e.g. "a2600 et"
       or a CHD e.g. "cdimono1 aidsawar" (Note: Not all CHD SLs are not currently available)
       or with MAME arguments e.g. "a2600 et -window"

Use dot to run mame without a machine e.g. ".", or with paramters ". -window"
If you have alreay loaded a machine (in current MAME version) you can use the MAME UI, filter on avaialable.

List saved state: ".list".

You can start a particular version of MAME with the command ".VVVV" where V is the version e.g. ".0252" or pass arguments e.g. ".0252 mrdo -window".

WARNING: Large downloads like CHD will take a while, each dot represents 1 MiB (about a floppy disk) you do the maths.

#######################################################################################################################
#                                                    Initializing                                                     #
#######################################################################################################################

Data Directory: E:\Mame New

Symbolic Links Enabled: False
!!! You can save a lot of disk space by enabling symbolic links, see the README.

=======================================================================================================================
=                                             Prepare source: MachineRom                                              =
=======================================================================================================================
Loading MachineRom metadata JSON E:\Mame New\_METADATA\MachineRom_mame-merged.json ......done.
Title:  MAME 0.258 ROM Set (Merged)
Version:        0258
=======================================================================================================================
=                                             Prepare source: MachineDisk                                             =
=======================================================================================================================
Loading MachineDisk metadata JSON E:\Mame New\_METADATA\MachineDisk_MAME_0.225_CHDs_merged.json ......done.

!!! FATAL ERROR: Cannot perform runtime binding on a null reference

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at Spludlow.MameAO.MameAOProcessor.Initialize()
   at Spludlow.MameAO.MameAOProcessor.Run()

If you want to submit an error report please copy and paste the text from here.
Select All (Ctrl+A) -> Copy (Ctrl+C) -> notepad -> paste (Ctrl+V)

Report issues here https://github.com/sam-ludlow/mame-ao/issues

Press any key to continue, program has crashed and will exit.

**Comment by sam-ludlow** [comment]
Hello @mcbruce76 this was fixed in 1.63.

You will have to manually update from the latest release ZIP from https://github.com/sam-ludlow/mame-ao/releases

Its because the machine disk source on arhive.org went sour.

Cheers
Sam

**Comment by sam-ludlow** [comment]
Closing

switched back to the original source used it has been fixed on archive.org and is good.
